import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript', 'prettier'),
  {
    // next-env.d.ts is generated by Next and is not ours to lint.
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      'research/**',
      'design-research/**',
      // A separate npm package with its own tsconfig, ESLint config and lockfile
      // (docs/automation-architecture.md §3). Never part of the site build.
      'automation/**',
    ],
  },
];

export default eslintConfig;
